export const rows = [
  {
    id: 1,
    name: "John Snow",
    email: "johnsnow@gmail.com",
    age: 35,
    phone: "(655)121-5454",
    access: "Admin",
  },
  {
    id: 2,
    name: "Cersi Lannister",
    email: "cersilannister@gmail.com",
    age: 42,
    phone: "(421)314-2288",
    access: "Admin",
  },
  {
    id: 3,
    name: "Jaime Lannister",
    email: "jaimelannister@gmail.com",
    age: 45,
    phone: "(422)982-6739",
    access: "Admin",
  },
  {
    id: 4,
    name: "Arya Stark",
    email: "aryastark@gmail.com",
    age: 16,
    phone: "(921)425-6742",
    access: "Manager",
  },
  {
    id: 5,
    name: "Daenerys Targaryen",
    email: "daenerystargaryen@gmail.com",
    age: 31,
    phone: "(655)121-5454",
    access: "Manager",
  },
  {
    id: 6,
    name: "Ever Melisandre",
    email: "evermelisandre@gmail.com",
    age: 150,
    phone: "(232)545-6483",
    access: "User",
  },
  {
    id: 7,
    name: "Ferrara Clifford",
    email: "ferraraclifford@gmail.com",
    age: 44,
    phone: "(655)121-5454",
    access: "User",
  },
  {
    id: 8,
    name: "Rossini Frances",
    email: "rossinifrances@gmail.com",
    age: 36,
    phone: "(222)444-5555",
    access: "User",
  },
  {
    id: 9,
    name: "Hervy Roxie",
    email: "hervyroxie@gmail.com",
    age: 65,
    phone: "(444)555-6239",
    access: "User",
  },
];


